version: '3'

services:
  karideo_db_service:
    image: mysql:latest
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    env_file:
      - ./config.env
    volumes:
      - /workspace/data/karideo/db:/var/lib/mysql

  karideo_adminer_service:
    image: adminer:latest
    restart: always
    ports:
      - 18079:8080
    links:
      - karideo_db_service:db

  karideo_back_service:
    build: back/
    restart: always
    image: org.kar.video.back
    ports:
      - 18080:18080
    env_file:
      - ./config.env
    links:
      - karideo_db_service:db
    volumes:
      - /workspace/data/karideo/media:/application/data


  karideo_front_service:
    build: front/
    restart: always
    image: org.kar.video.front
    container_name: karideo
    ports:
      #- 15081:4200
      - 15081:80