version: "3.7"

services:
  REST_video_service:
    build: src 
    restart: always
    image: yui.heero/video_rest_api
    container_name: video_rest_api
    ports:
      - "15080:80"
    volumes:
      - /workspace/data/karideo/media:/application/data
      - ./default_images:/default_images:ro
    env_file:
      - ./config.env




