version: "3.7"

services:
  REST_video_service:
    build: src 
    restart: always
    environment:
      SANIC_DB_ADDRESS: postgres
      SANIC_DB_NAME: karideo
      SANIC_DB_USER: postgres
      SANIC_DB_PASSWORD: postgres
    image: yui.heero/video_rest_api
    container_name: video_rest_api
    ports:
      - "15080:80"
    volumes:
      - ./data/data_karideo:/application/data

