version: "3.7"

services:
  karideo_postgres:
    restart: always
    image: postgres:alpine
    environment:
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: karideo
    ports:
      - "43522:5432"
    volumes:
      - ./data:/var/lib/postgresql/data

